version: '3.8'
services:
  app:
    build: .
    env_file: ./config/.env
    container_name: paperon_app
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      - DB_HOST=$DB_HOST
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
      - DB_NAME=$DB_NAME
      - DB_PORT=$DB_PORT
      - JWT_SECRET=$JWT_SECRET
      - ADMIN_EMAIL=$ADMIN_EMAIL
      - ENABLE_REGISTER=true
    restart: unless-stopped